### ISSUE TITLE
Update payload_data schema to 1-0-4

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-ruby-tracker#102]

**Comment by juriglx** [comment]
It also seems that the stm field [should be a string](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/payload_data/jsonschema/1-0-4#L247-L249) instead of an integer.

**Comment by chuwy** [comment]
You're right @juriglx. Thanks.
