### ISSUE TITLE
Memory leaks when using SnowplowTracker::AsyncEmitter 

### ISSUE THREAD

**Issue by allanoneflare** [snowplow/snowplow-ruby-tracker#107]
When using AsyncEmitter, threads keeps increasing which results to memory growing overtime until host run out of resource and cant create thread anymore, this also makes the parent process becomes unresponsive.  

![screen shot 2018-06-13 at 5 17 34 pm](https://user-images.githubusercontent.com/23020018/41448327-5b98c8c8-709d-11e8-874c-279efa230fda.png)

**Comment by BenFradet** [comment]
Thanks for the report, if you manage to track down the bug, we'll be happy to review a PR :+1:

**Comment by allanoneflare** [comment]
hi @BenFradet, basically we are instantiating `SnowplowTracker::AsyncEmitter` every time we track an event, this seems to create new thread all the time which never gets killed or terminated. maybe an explicit thread terminate on emitter object would help. otherwise we need adjust our code so that only a single emitter object will be created that will be used application wide, I'm not sure if this is the recommended approach but I cant find it on wiki. 

in the meantime, we just use `SnowplowTracker::Emitter` since we mostly do our tracking process within sidekiq

**Comment by BenFradet** [comment]
The recommended way is indeed to only have one `AsyncEmitter` for your whole application.

**Comment by allanoneflare** [comment]
would be good
