### ISSUE TITLE
Is this Project dead?

### ISSUE THREAD

**Issue by askdesigners** [snowplow/snowplow-ruby-tracker#116]
The last update to this was more than a year ago, and it doesn't support the latest version of Ruby at all. 
Are there any plans to revive this?

**Comment by paulboocock** [comment]
Hey @askdesigners 
We're actually working on updating this tracker right now, so your question is well timed! We've just put together a new Ruby Tracker example using Rails: https://github.com/snowplow-incubator/snowplow-ruby-tracker-examples/ and we're now starting to work on updating it and its dependencies.

**Comment by askdesigners** [comment]
WooHoo! I'll follow the progress closely. Thanks for the work! It would be great to not need to build a workaround to get data flowing from our rails app.

**Comment by paulboocock** [comment]
If there are any particular issues you are facing with this library and your rails app, it'd be great to hear them to make sure we fix everything in the next release.

**Comment by pbstriker38** [comment]
Having a buffer flush timeout would be a great option. We initially looked into using the buffer, but this caused some events to get stuck in the buffer for a long time during low activity.

**Comment by mscwilson** [comment]
Hi @askdesigners, just for clarity: the Ruby tracker v0.6.0 does currently work with Ruby 2.1+, including 3.0. I've updated the docs now (they used to specify Ruby <= 2.1).

The [Ruby tracker demo Rails app](https://github.com/snowplow-incubator/snowplow-ruby-tracker-examples/) linked above uses Ruby 3.0 with Rails v6.1. Good luck getting that data flowing!
