### ISSUE TITLE
Add "app" and "web" to supported platforms

### ISSUE THREAD

**Issue by mscwilson** [snowplow/snowplow-ruby-tracker#136]
The [Snowplow tracker protocol](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/snowplow-tracker-protocol/#common-parameters-platform-and-event-independent) allows the platform to be defined, e.g "mob" for an event that occured on mobile.

Of these 8 supported platforms, the Ruby tracker currently only supports 6. "Web" and "app" are missing. Add them in as allowed platforms.

**Comment by paulboocock** [comment]
Well thats a surprise, Good find!
