### ISSUE TITLE
JSONs should be URI-encoded if not Base64-encoded

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-ruby-tracker#64]

**Comment by fblundun** [comment]
Closing since this is already done [here](https://github.com/snowplow/snowplow-ruby-tracker/blob/067b2c6ccfc5074d8ba5b9666d7432fe1838b357/lib/snowplow-tracker/emitters.rb#L156)

**Comment by alexanderdean** [comment]
Thanks Fred
